backend = "glx";
vsync = true;
use-damage = false;
glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;
unredir-if-possible = false;
fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;
no-fading-openclose = true;

# The Blur
blur: {
  method = "dual_kawase";
  strength = 5;
  background = true;
  background-frame = false;
  background-fixed = false;
}

corner-radius = 0;
shadow = true;
shadow-exclude = [
  "name = 'Polybar tray window'",
  "class_g = 'Polybar'",
  "class_g = 'st-256color'",
  "class_g = 'Alacritty'"
];

focus-exclude = [ 
  "class_g = 'st-256color'",
  "class_g = 'Alacritty'"
];

# This prevents the blur from bleeding out of the rounded corners
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

# Force the terminal to be 85% opaque so blur is visible
opacity-rule = [
  "85:class_g = 'st-256color'",
  "85:class_g = 'st'"
];

# Ensure Picom is actively trying to blur windows
blur-background-frame = false;
blur-background-fixed = true;
blur-background = true;

# FT-Labs Animation Settings
animations = true;
animation-stiffness = 300.0;
animation-dampening = 25.0;
animation-clamping = true;
animation-mass = 1.0;
animation-for-open-window = "zoom"; # Choices: zoom, slide-up, slide-down
