backend = "egl";
vsync = true;
use-damage = false; # Important for Intel Iris Xe to prevent flickering
xrender-sync-fence = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
unredir-if-possible = false;
shadow = false;

# The Blur
blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
  background-frame = false;
  background-fixed = false;
}

# Rounded Corners (The Hyprland look)
corner-radius = 0;

shadow-exclude = [
  "name = 'Polybar tray window'",
  "class_g = 'Polybar'"
];

# This prevents the blur from bleeding out of the rounded corners
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Force the terminal to be 85% opaque so blur is visible
opacity-rule = [
  "85:class_g = 'st-256color'",
  "85:class_g = 'st'"
];

# Ensure Picom is actively trying to blur windows
blur-background-frame = false;
blur-background-fixed = true;
blur-background = true;

# FT-Labs Animation Settings
animations = true;
animation-stiffness = 300.0;
animation-dampening = 25.0;
animation-clamping = true;
animation-mass = 1.0;
animation-for-open-window = "zoom"; # Choices: zoom, slide-up, slide-down
